// Mocks generated by Mockito 5.4.4 from annotations
// in graph_sample/test/presentation/bloc/blood_glucose_graph_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:graph_sample/domain/entity/blood_glucose_graph_entity.dart'
    as _i2;
import 'package:graph_sample/domain/use_case/get_blood_glucose_graph_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBloodGlucoseGraphEntity_0 extends _i1.SmartFake
    implements _i2.BloodGlucoseGraphEntity {
  _FakeBloodGlucoseGraphEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetBloodGlucoseGraphUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBloodGlucoseGraphUseCase extends _i1.Mock
    implements _i3.GetBloodGlucoseGraphUseCase {
  MockGetBloodGlucoseGraphUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BloodGlucoseGraphEntity> execute([dynamic param]) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [param],
        ),
        returnValue: _i4.Future<_i2.BloodGlucoseGraphEntity>.value(
            _FakeBloodGlucoseGraphEntity_0(
          this,
          Invocation.method(
            #execute,
            [param],
          ),
        )),
      ) as _i4.Future<_i2.BloodGlucoseGraphEntity>);
}
