// Mocks generated by Mockito 5.4.4 from annotations
// in graph_sample/test/data/repository/blood_glucose_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:graph_sample/common/data/response_model.dart' as _i2;
import 'package:graph_sample/data/data_source/data_source.dart' as _i3;
import 'package:graph_sample/data/model/blood_glucose_graph_response_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseModel_0<T> extends _i1.SmartFake
    implements _i2.ResponseModel<T> {
  _FakeResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSource extends _i1.Mock implements _i3.DataSource {
  MockDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ResponseModel<_i5.BloodGlucoseGraphModel>>
      getBloodGlucoseGraph() => (super.noSuchMethod(
            Invocation.method(
              #getBloodGlucoseGraph,
              [],
            ),
            returnValue:
                _i4.Future<_i2.ResponseModel<_i5.BloodGlucoseGraphModel>>.value(
                    _FakeResponseModel_0<_i5.BloodGlucoseGraphModel>(
              this,
              Invocation.method(
                #getBloodGlucoseGraph,
                [],
              ),
            )),
          ) as _i4.Future<_i2.ResponseModel<_i5.BloodGlucoseGraphModel>>);
}
